CREATE TABLE person (
   id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(50) NOT NULL,
   email VARCHAR(50) NOT NULL,
   photo VARCHAR(50) NOT NULL,
   birthDate DATE NOT NULL,
   updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP()
);